apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: devops-8268-ecr
      containers:
      - name: nginx
        image: 826846563965.dkr.ecr.ap-northeast-2.amazonaws.com/watchcon:13
        ports:
        - containerPort: 80        
        resources:
         requests:
           cpu: "1000m"

           memory: "1Gi"
         limits:
           cpu: "1500m"

           memory: "1.5Gi"
