apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchcon-deployment
  labels:
    app: watchcon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchcon
  template:
    metadata:
      labels:
        app: watchcon
    spec:
      imagePullSecrets:
      - name: devops-8268-ecr
      containers:
      - name: watchcon
        image: 826846563965.dkr.ecr.ap-northeast-2.amazonaws.com/watchcon:13
        ports:
        - containerPort: 8080     
        resources:
         requests:
           cpu: "500m"

           memory: "1Gi"
         limits:
           cpu: "800m"

           memory: "1.5Gi"
